# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170911_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catecory',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='catecory',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='blog.Catecory'),
            preserve_default=False,
        ),
    ]
