# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170912_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.User')),
            ],
            bases=('blog.user',),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.User')),
            ],
            bases=('blog.user',),
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.User')),
            ],
            bases=('blog.user',),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-post_date']},
        ),
    ]
